// GENERATED by design/build_tokens.py from design/tokens.json. Do not edit.

export const brand = {
  "navy": "#0c2340",
  "red": "#c8102e",
  "gold": "#ffb549",
  "cream": "#fffaf0",
  "paper": "#f4efe5",
  "line": "#d9d1c3",
  "inkSoft": "#516175",
} as const;

/**
 * Data-state colours. `absent` covers both "not evaluated" and "outside the
 * scope of this rule" — it must never be read as compliance.
 */
export const dataColor = {
  "fails": "#c83a3a",
  "meets": "#0c2340",
  "absent": "#e4dfd6",
  "muted": "#647184",
  "road": "#0c2340",
} as const;

export const category = {
  "administrative_or_community_appeal": {
    "value": "#0c2340",
    "label": "Administrative/community appeal"
  },
  "parking_supply": {
    "value": "#c83a3a",
    "label": "Parking supply"
  },
  "use_spacing_separation": {
    "value": "#0072ce",
    "label": "Use spacing/separation"
  },
  "setbacks_yards": {
    "value": "#e57f00",
    "label": "Setbacks/yards"
  },
  "nonconforming_use_or_structure": {
    "value": "#43617f",
    "label": "Nonconforming use/structure"
  },
  "lot_coverage": {
    "value": "#d85b68",
    "label": "Lot coverage"
  },
  "lot_dimensions": {
    "value": "#75a7db",
    "label": "Lot dimensions"
  },
  "height": {
    "value": "#b96f00",
    "label": "Height"
  },
  "parking_layout": {
    "value": "#173e67",
    "label": "Parking layout"
  },
  "screening_landscaping": {
    "value": "#a92f43",
    "label": "Screening/landscaping"
  },
  "signs_billboards": {
    "value": "#5f8fbe",
    "label": "Signs/billboards"
  },
  "floor_area_bulk": {
    "value": "#d2a944",
    "label": "Floor area/bulk"
  },
  "multiple_buildings": {
    "value": "#647184",
    "label": "Multiple buildings"
  },
  "open_recreation_space": {
    "value": "#8f5261",
    "label": "Open/recreation space"
  },
  "fences_walls": {
    "value": "#90b8e8",
    "label": "Fences/walls"
  },
  "loading": {
    "value": "#927035",
    "label": "Loading"
  },
  "unspecified": {
    "value": "#73777d",
    "label": "Request not specified"
  }
} as const;

export const font = {
  "serif": "\"Source Serif 4\", \"Source Serif 4 Fallback\", Georgia, \"Times New Roman\", serif",
  "sans": "\"Inter\", \"Inter Fallback\", system-ui, -apple-system, Arial, sans-serif",
} as const;

export const tracking = {
  "caps": "0.08em",
  "display": "-0.018em",
} as const;

/** Frozen-poster geometry, matching the printed conference exhibits. */
export const exhibit = {
  "width": 1600,
  "height": 1100,
  "map": {
    "x": 48,
    "y": 205,
    "width": 1015,
    "height": 680
  },
  "column": {
    "x": 1120
  }
} as const;

export type BrandColor = keyof typeof brand;
export type DataColor = keyof typeof dataColor;
export type CategoryKey = keyof typeof category;
