"""GENERATED by design/build_tokens.py from design/tokens.json. Do not edit."""

from __future__ import annotations

# Brand
NAVY = "#0c2340"
RED = "#c8102e"
GOLD = "#ffb549"
CREAM = "#fffaf0"
PAPER = "#f4efe5"
LINE = "#d9d1c3"
INKSOFT = "#516175"

# Data states
DATA_FAILS = "#c83a3a"
DATA_MEETS = "#0c2340"
DATA_ABSENT = "#e4dfd6"
DATA_MUTED = "#647184"
DATA_ROAD = "#0c2340"

CATEGORY_COLORS = {
    "administrative_or_community_appeal": "#0c2340",
    "parking_supply": "#c83a3a",
    "use_spacing_separation": "#0072ce",
    "setbacks_yards": "#e57f00",
    "nonconforming_use_or_structure": "#43617f",
    "lot_coverage": "#d85b68",
    "lot_dimensions": "#75a7db",
    "height": "#b96f00",
    "parking_layout": "#173e67",
    "screening_landscaping": "#a92f43",
    "signs_billboards": "#5f8fbe",
    "floor_area_bulk": "#d2a944",
    "multiple_buildings": "#647184",
    "open_recreation_space": "#8f5261",
    "fences_walls": "#90b8e8",
    "loading": "#927035",
    "unspecified": "#73777d"
}

CATEGORY_LABELS = {
    "administrative_or_community_appeal": "Administrative/community appeal",
    "parking_supply": "Parking supply",
    "use_spacing_separation": "Use spacing/separation",
    "setbacks_yards": "Setbacks/yards",
    "nonconforming_use_or_structure": "Nonconforming use/structure",
    "lot_coverage": "Lot coverage",
    "lot_dimensions": "Lot dimensions",
    "height": "Height",
    "parking_layout": "Parking layout",
    "screening_landscaping": "Screening/landscaping",
    "signs_billboards": "Signs/billboards",
    "floor_area_bulk": "Floor area/bulk",
    "multiple_buildings": "Multiple buildings",
    "open_recreation_space": "Open/recreation space",
    "fences_walls": "Fences/walls",
    "loading": "Loading",
    "unspecified": "Request not specified"
}

CATEGORY_ORDER = [
    "administrative_or_community_appeal",
    "parking_supply",
    "use_spacing_separation",
    "setbacks_yards",
    "nonconforming_use_or_structure",
    "lot_coverage",
    "lot_dimensions",
    "height",
    "parking_layout",
    "screening_landscaping",
    "signs_billboards",
    "floor_area_bulk",
    "multiple_buildings",
    "open_recreation_space",
    "fences_walls",
    "loading",
]
