"""Centralized constants for zoning analysis."""

# Preemption / proposed legislation thresholds
PROPOSED_MIN_SQFT = 1500
PROPOSED_MIN_DWELLING_SQFT = 500
CURRENT_MIN_DWELLING_ASSUMPTION = 1000

# Residential zoning districts
RESIDENTIAL_ZONES = ['R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'SD1', 'SD2']

# Use-code groupings for preemption analysis
TARGET_KEYS = [
    'SINGLE FAMILY', 'TWO FAMILY', 'FOUR FAMILY', 'ROW HOUSE', 'THREE FAMILY',
    'APT-FLAT GARDEN TYPE', 'APT-WALK UP', 'MIXED USE-APT', 'HALF DUPLEX',
    'FIVE FAMILY', 'APT-W/ ELEVATOR', 'DUPLEX', 'COOPERATIVE', 'APT-HI-RISE',
    'APT-FLAT SLAB TYPE', 'SIX FAMILY', 'ASSISTED LIVING RESIDENCE',
    'PARSONAGE', 'NURSING HOME', 'RESIDENTIAL - CONDO', 'CARRIAGE HOUSE',
    'MIXED USE-CONDO',
]

DUPLEX_KEYS = ['TWO FAMILY', 'DUPLEX', 'HALF DUPLEX']

MULTI_FAMILY_KEYS = [
    'THREE FAMILY', 'FOUR FAMILY', 'FIVE FAMILY', 'SIX FAMILY', 'ROW HOUSE',
    'APT-FLAT GARDEN TYPE', 'APT-WALK UP', 'APT-W/ ELEVATOR', 'COOPERATIVE',
    'APT-HI-RISE', 'APT-FLAT SLAB TYPE',
]

ADU_KEYS = ['CARRIAGE HOUSE']
