#!/usr/bin/env python3
"""Generate design tokens for every stack from design/tokens.json.

The palette had forked before this existed: the website's red was #c8102e while
the flagship parcel exhibits used #c83a3a, with 71 distinct colours in the
Python exhibits against 29 on the web and only 22 shared. Generating both from
one file is what stops that recurring.

Writes:
    sites/land-forum/app/tokens.css       CSS custom properties
    sites/land-forum/lib/tokens.ts        typed module for the renderer
    src/strongtowns_detroit/design/tokens.py   for the Python exhibit builders

Usage:
    python design/build_tokens.py [--check]

--check exits non-zero if any generated file is stale, for CI.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
SOURCE = HERE / "tokens.json"

BANNER = "GENERATED by design/build_tokens.py from design/tokens.json. Do not edit."


def load() -> dict:
    return json.loads(SOURCE.read_text(encoding="utf-8"))


def _kebab(name: str) -> str:
    out = []
    for char in name:
        if char.isupper():
            out.append("-")
            out.append(char.lower())
        else:
            out.append(char)
    return "".join(out).replace("_", "-")


def _entries(group: dict) -> list[tuple[str, str]]:
    """Yield (name, value) for token entries, skipping $-prefixed metadata."""
    return [
        (key, entry["value"])
        for key, entry in group.items()
        if not key.startswith("$") and isinstance(entry, dict) and "value" in entry
    ]


def render_css(tokens: dict) -> str:
    lines = [f"/* {BANNER} */", "", ":root {"]

    lines.append("  /* Brand */")
    for name, value in _entries(tokens["color"]["brand"]):
        lines.append(f"  --{_kebab(name)}: {value};")

    lines.append("")
    lines.append("  /* Data states — never encode status by colour alone. */")
    for name, value in _entries(tokens["color"]["data"]):
        lines.append(f"  --data-{_kebab(name)}: {value};")

    lines.append("")
    lines.append("  /* Type */")
    for name, value in _entries(tokens["font"]):
        lines.append(f"  --font-{_kebab(name)}: {value};")
    for name, value in _entries(tokens["tracking"]):
        lines.append(f"  --track-{_kebab(name)}: {value};")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def render_ts(tokens: dict) -> str:
    brand = dict(_entries(tokens["color"]["brand"]))
    data = dict(_entries(tokens["color"]["data"]))
    fonts = dict(_entries(tokens["font"]))
    tracking = dict(_entries(tokens["tracking"]))
    categories = {
        key: entry
        for key, entry in tokens["color"]["category"].items()
        if not key.startswith("$")
    }
    exhibit = {k: v for k, v in tokens["exhibit"].items() if not k.startswith("$")}

    def obj(mapping: dict, indent: str = "  ") -> str:
        return "\n".join(
            f'{indent}{json.dumps(k)}: {json.dumps(v)},' for k, v in mapping.items()
        )

    return f"""// {BANNER}

export const brand = {{
{obj(brand)}
}} as const;

/**
 * Data-state colours. `absent` covers both "not evaluated" and "outside the
 * scope of this rule" — it must never be read as compliance.
 */
export const dataColor = {{
{obj(data)}
}} as const;

export const category = {json.dumps(categories, indent=2)} as const;

export const font = {{
{obj(fonts)}
}} as const;

export const tracking = {{
{obj(tracking)}
}} as const;

/** Frozen-poster geometry, matching the printed conference exhibits. */
export const exhibit = {json.dumps(exhibit, indent=2)} as const;

export type BrandColor = keyof typeof brand;
export type DataColor = keyof typeof dataColor;
export type CategoryKey = keyof typeof category;
"""


def render_python(tokens: dict) -> str:
    brand = dict(_entries(tokens["color"]["brand"]))
    data = dict(_entries(tokens["color"]["data"]))
    categories = {
        key: entry
        for key, entry in tokens["color"]["category"].items()
        if not key.startswith("$")
    }

    def const(mapping: dict) -> str:
        return "\n".join(
            f'{name.upper().replace("-", "_")} = "{value}"'
            for name, value in mapping.items()
        )

    category_colors = {k: v["value"] for k, v in categories.items()}
    category_labels = {k: v["label"] for k, v in categories.items()}

    return f'''"""{BANNER}"""

from __future__ import annotations

# Brand
{const(brand)}

# Data states
{const({f"data_{k}": v for k, v in data.items()})}

CATEGORY_COLORS = {json.dumps(category_colors, indent=4)}

CATEGORY_LABELS = {json.dumps(category_labels, indent=4)}

CATEGORY_ORDER = [
{chr(10).join(f'    "{key}",' for key in categories if key != "unspecified")}
]
'''


TARGETS = [
    (Path("sites/land-forum/app/tokens.css"), render_css),
    (Path("sites/land-forum/lib/tokens.ts"), render_ts),
    (Path("src/strongtowns_detroit/design/tokens.py"), render_python),
]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    tokens = load()
    stale: list[Path] = []

    for relative, render in TARGETS:
        path = ROOT / relative
        content = render(tokens)
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            print(f"  ok      {relative}")
            continue
        if args.check:
            stale.append(relative)
            print(f"  STALE   {relative}")
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.name == "tokens.py" and not (path.parent / "__init__.py").exists():
            (path.parent / "__init__.py").write_text(
                '"""Generated design tokens."""\n', encoding="utf-8"
            )
        path.write_text(content, encoding="utf-8")
        print(f"  written {relative}")

    if stale:
        print(f"\n{len(stale)} generated file(s) stale. Run: python design/build_tokens.py")
        sys.exit(1)


if __name__ == "__main__":
    main()
