import Link from 'next/link';
import FeaturedBzaMap from '../components/FeaturedBzaMap';
export default function Home(){return <main id="main">
  <header className="site-header"><Link className="wordmark" href="/">LAND FORUM</Link><nav aria-label="Primary"><Link href="/atlas/">BZA Atlas</Link><Link href="/methods/">Methods & sources</Link></nav></header>
  <section className="hero"><div className="hero-copy"><p className="kicker">DETROIT · BOARD OF ZONING APPEALS</p><h1>Detroit’s zoning appeals,<br/><em>mapped and explained.</em></h1><p className="hero-dek">Explore the cases recorded in Detroit’s zoning appeals minutes. Follow the hearings, read the source records, and create a map to share.</p><div className="hero-actions"><Link className="button button-primary" href="/atlas/">Explore the atlas</Link><Link className="button button-quiet" href="/methods/">How to read the records</Link></div></div><FeaturedBzaMap/></section>
  <section className="project-band"><p className="kicker">THE FIRST SERIES</p><div className="project-grid"><div><h2>What relief are Detroiters asking for?</h2><p>Each point represents a case. Color shows the primary relief requested; size shows how many hearings appear in the available minutes. Open the atlas to examine the cases behind the pattern.</p></div><Link className="project-link" href="/atlas/">Explore and create a graphic ↗</Link></div></section>
  <section className="about" id="about"><p className="kicker">ABOUT LAND FORUM</p><div><h2>Public records, made easier to explore.</h2><div className="about-columns"><p>Land Forum is a project of Strong Towns Detroit. We publish maps and explanations drawn from Detroit Board of Zoning Appeals minutes.</p><p>The atlas connects each case to its hearing record and available source minutes. New publications will explore specific questions using the same evidence.</p></div></div></section>
  <footer><div className="footer-top"><div className="wordmark">LAND FORUM</div><p>A project of Strong Towns Detroit.</p></div><div className="footer-meta"><p>Coverage follows the available minutes and may be incomplete. The atlas shows its dataset dates and mapping limitations.</p><nav><Link href="/atlas/">BZA Atlas</Link><Link href="/methods/">Methods & sources</Link><Link href="/graphics/bza/">Chart studio</Link></nav></div></footer>
</main>;}
