"""Opinionated, aspect-ratio-aware HTML graphics composition."""

from strongtowns_detroit.graphics.builder import (
    BuildRecord,
    GraphicBuildSystem,
    GraphicDefinition,
    GraphicProject,
    graphic_definition,
)
from strongtowns_detroit.graphics.charts import (
    BarArrangement,
    BarChartStyle,
    BarOrientation,
    BarPattern,
    BarSeries,
    ChartAlignment,
    NumericAxis,
    bar_chart,
)
from strongtowns_detroit.graphics.detroit import (
    LegendComparator,
    LegendItem,
    LegendOrders,
    MapLegend,
    MobileMapInset,
    MobileMapInsetKind,
    MobileMapPocket,
    bza_hearing_marker_area,
    bza_hearing_marker_radius,
    build_map_graphic,
    map_on_mobile,
    wide_map_with_legend_on_mobile,
)

from strongtowns_detroit.graphics.model import (
    CONFERENCE_LANDSCAPE,
    INSTAGRAM_PORTRAIT,
    INSTAGRAM_STORY,
    INSTAGRAM_SQUARE,
    AspectRatio,
    GraphicTheme,
    GraphicFormat,
    GraphicFormatSpec,
    GRAPHIC_FORMAT_SPECS,
    MapMarkerStyle,
)
from strongtowns_detroit.graphics.maps import (
    WebMercatorBasemap,
    categorical_proportional_symbol_map,
)
from strongtowns_detroit.graphics.svg import (
    Graphic,
    MobileMapLayout,
    MobileMapSegment,
    SvgComponent,
    SvgRegion,
    apply_layout_sidecar,
    render_graphic_svg,
    render_graphic_canvas,
    write_graphic_bundle,
    write_graphic_variants,
)
from strongtowns_detroit.graphics.typography import (
    MOBILE_TYPOGRAPHY,
    MobileTypography,
)

__all__ = [
    "CONFERENCE_LANDSCAPE",
    "INSTAGRAM_PORTRAIT",
    "INSTAGRAM_STORY",
    "INSTAGRAM_SQUARE",
    "AspectRatio",
    "BarArrangement",
    "BarChartStyle",
    "BarOrientation",
    "BarPattern",
    "BarSeries",
    "ChartAlignment",
    "BuildRecord",
    "GraphicBuildSystem",
    "GraphicDefinition",
    "GraphicProject",
    "graphic_definition",
    "GraphicFormat",
    "GraphicFormatSpec",
    "GRAPHIC_FORMAT_SPECS",
    "GraphicTheme",
    "LegendComparator",
    "LegendItem",
    "LegendOrders",
    "MapLegend",
    "MapMarkerStyle",
    "NumericAxis",
    "WebMercatorBasemap",
    "categorical_proportional_symbol_map",
    "Graphic",
    "MobileMapLayout",
    "MobileMapSegment",
    "MobileMapInset",
    "MobileMapInsetKind",
    "MobileMapPocket",
    "MobileTypography",
    "MOBILE_TYPOGRAPHY",
    "bza_hearing_marker_area",
    "bza_hearing_marker_radius",
    "build_map_graphic",
    "map_on_mobile",
    "wide_map_with_legend_on_mobile",
    "SvgComponent",
    "SvgRegion",
    "apply_layout_sidecar",
    "bar_chart",
    "render_graphic_svg",
    "render_graphic_canvas",
    "write_graphic_bundle",
    "write_graphic_variants",
]
